### ISSUE TITLE
Zip code does not matched

### ISSUE THREAD

**Issue by kenjimanishi** [makeupsomething/japan-address-autofill#18]
Hi there,

I am a user of this service.
Thanks again.

I found that the zip code "1960035" does not match.
The zip code "1960035" actually exists.
https://www.post.japanpost.jp/cgi-zip/zipcode.php?pref=13&city=1132070&id=49931

Maybe there are other zip codes that cannot be matched...
Could you please confirm that you may not be registered?

**Comment by makeupsomething** [comment]
Thank you for using this library!

Il check this tonight.

**Comment by makeupsomething** [comment]
Yes this zip code is missing.

I can add it this week or I would be happy to accept a pull request with the zip code or any more that you find missing 🙏

**Comment by makeupsomething** [comment]
Never mind, I've updated to include this zipcode 👍 

But it is hard to maintain all the zipcodes, so if you ever find more missing I would really appreciate a PR. 
Thank you!

**Comment by kenjimanishi** [comment]
@makeupsomething 
Thanks for your response!
I have confirmed that the zip code "1960035" will be matched.

I'll send out a PR if I find a zip code that won't be matched in the future.
