### ISSUE TITLE
Zip code does not matched

### ISSUE THREAD

**Issue by kenjimanishi** [makeupsomething/japan-address-autofill#19]
Hi there,

I am a user of this service.
Thanks again.

I found that the zip code "501-0439" does not match.
The zip code "501-0439" actually exists.
https://www.post.japanpost.jp/cgi-zip/zipcode.php?pref=21&city=1214210&id=80602&merge=

I wanted to create a pull request, and when I pushed it, it didn't seem to have permission...
```
ERROR: Permission to makeupsomething/japan-address-autofill.git denied to MY_NAME.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

I would appreciate it if you could check it.

**Comment by makeupsomething** [comment]
Hi 👋

Thank you again for using this library and thank you for contributing. 

To push you PR you will need to make a fork of this repository and make your changes in there. Then you can make the PR upstream into this repository.

**Comment by kenjimanishi** [comment]
@makeupsomething 

Thank you for your explanation.
I created a PR. https://github.com/makeupsomething/japan-address-autofill/pull/20

I would appreciate it if you could check it.

**Comment by makeupsomething** [comment]
Thank you for contributing, I have merged your PR and updated the package.
