### ISSUE TITLE
Add local data

### ISSUE THREAD

**Issue by makeupsomething** [makeupsomething/japan-address-autofill#2]
In order to reduce the amount of api calls the library needs to make we can make use of a local cache of data. We can then fall back to using an api call if the local data fails for some reason.

**Comment by chandan1794** [comment]
What are the scenarios when local cache can fail?
Can cache be invalid after a certain amount of time?

**Comment by makeupsomething** [comment]
@chandan1794
I think cache in this case was the wrong word, I have updated the issue title. 

I have added zip code data locally here in this branch https://github.com/makeupsomething/japan-address-autofill/tree/feature/add-local-data/zipdata

I think in general it should never fail as it is the same as the API would return. The only time it would become invalid/outdated is if Japan Post Service update their codes or add new codes. In which case we would fallback to the API which is supposed to always be up to date.
